name: Whisprr

services:
  postgres:
    container_name: Whisprr.Postgres
    image: postgres:18
    environment:
      POSTGRES_DB: whisprr-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432

  redis:
    container_name: Whisprr.Redis
    image: redis/redis-stack:latest
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
      - 8001:8001

  rabbitmq:
    container_name: Whisprr.RabbitMQ
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: whisprr
      RABBITMQ_DEFAULT_PASS: whisprr
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 5672:5672 # AMQP port
      - 15672:15672 # Management UI

  auth-service:
    container_name: Whisprr.AuthService
    build:
      context: .
      dockerfile: services/Whisprr.AuthService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=whisprr_auth;Username=postgres;Password=postgres
      - Jwt__Key=dev-secret-key-minimum-32-characters-long-for-testing
      - Jwt__Issuer=whisprr-auth
      - Jwt__Audience=whisprr-api
      - MessageBroker__Host=rabbitmq://rabbitmq:5672
      - MessageBroker__Username=whisprr
      - MessageBroker__Password=whisprr
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
