name: Whisprr

services:
  postgres:
    container_name: Whisprr.Postgres
    image: postgres:18
    environment:
      POSTGRES_DB: whisprr-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432

  redis:
    container_name: Whisprr.Redis
    image: redis/redis-stack:latest
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
      - 8001:8001

  rabbitmq:
    container_name: Whisprr.RabbitMQ
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: whisprr
      RABBITMQ_DEFAULT_PASS: whisprr
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 5672:5672 # AMQP port
      - 15672:15672 # Management UI

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
